---
-name: Deploy to tomcat
 hosts: web
 become: yes
 
 tasks:
  
 -name: copy war
  src: target/maven-web
  dest: /opt/tomcat/webapps/maven-web
  
 -name: stop
  shell: /opt/tomcat/bin/shutdown.sh
  
 -name: start
  shell: /opt/start/bin/shartup.sh
