---
- name: Deploy to tomcat
  hosts: web
  become: yes
 
  tasks:
  
   - name: copy war
     copy:
     
       src: target/maven-web
       dest: /opt/tomcat/webapps/maven-web
  
   - name: stop
     shell: /opt/tomcat/bin/shutdown.sh
  
   - name: start tomcat
     shell: /opt/tomcat/bin/startup.sh
